import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import { ShoppingCartProvider } from '@/context/ShoppingCartContext'
import ShoppingCart from '@/components/ShoppingCart'

const fontHeading = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={(fontHeading.variable, fontBody.variable, 'antialiased')}>
        <ShoppingCartProvider>
          <ShoppingCart />
          {children}
        </ShoppingCartProvider>
      </body>
    </html>
  )
}
