FROM node:20

EXPOSE 9090

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

RUN mkdir /app
WORKDIR /app
ADD package.json yarn.lock .env data /app/
ADD . /app
RUN yarn --pure-lockfile && yarn playwright install && yarn playwright install-deps
# RUN yarn --pure-lockfile
RUN npx prisma generate
RUN npx prisma migrate deploy

CMD ["yarn", "dev"] 